name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with: {node-version: 20, cache: 'yarn'}

      - run: yarn -y

      - run: yarn test
